services:
  gigapi:
    image: ghcr.io/gigapi/gigapi:latest
    container_name: gigapi
    hostname: gigapi
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - "7971:7971"
      - "8082:8082"
    environment:
      - GIGAPI_ENABLED=true
      - GIGAPI_MERGE_TIMEOUT_S=10
      - GIGAPI_ROOT=/data
      - PORT=7971
  hep-gigapi:
    image: ghcr.io/sipcapture/hep-gigapi:latest
    container_name: hep-gigapi
    hostname: hep-gigapi
    ports:
      - "9060:9060/udp"
      - "9060:9060/tcp"
    environment:
      - PORT=9060
      - INFLUX_DBURL=http://gigapi:7971
  hepgen:
    image: qxip/docker-hepgen
    container_name: hepgen
    environment:
    - "HEP_SERVER=hep-gigapi"
    - "HEP_PORT=9060"
    - "HEP_PROTO=udp4"
    - "LOOP=400"
    - "SLEEP=1800"
    restart: unless-stopped
    depends_on:
      - hep-gigapi
